"""Integration test against a real JITX-produced XML fixture.

`golden.xml` is generated by the JITX IDE (see tests/fixtures/README.md)
and is intentionally not always committed. Skip cleanly when it is
missing so contributors without the IDE can still run the suite.
"""

import pytest

from jitx_pnp import pick_and_place


def test_pick_and_place_matches_golden(golden_xml, golden_csv):
    if not golden_xml.exists() or not golden_csv.exists():
        pytest.skip(
            "golden.xml/golden.csv not present; "
            "regenerate per tests/fixtures/README.md to run this test"
        )
    result = pick_and_place(golden_xml)
    expected = golden_csv.read_text()
    assert result == expected
